@startuml addStudent

class ViewStudentForm {
    - classroom_id: bigint
    - token: string

    + view_student(token, classroom_id)
    + show_all_student(students)
}

class IStudentForm <<interface>> {
    + view_student(token, classroom_id)
    + show_all_student(students)
}

class StudentController {
    + view_profile(token, classroom_id)
}

class ClassroomMember {
    - id: bigint
    - user_id: bigint
    - classroom_id: bigint
    - created_at: datetime

    + get_id(): bigint
    + get_user_id(): bigint
    + set_user_id(bigint)
    + get_classroom_id(): bigint
    + set_classroom_id(bigint)
    + get_created_at(): datetime
    + get_updated_at(): datetime
}

class IClassroomMemberDB <<interface>> {
    + create(classroom_id, user_id): void
    + read(classroom_id)
    + read(user_id)
    + read(classroom_member_id)
    + read(classroom_id, user_id)
    + update_rollcall(classroom_member_id, created_at, is_presented)
    + update_bonus_point(classroom_member_id, created_at, point)
    + update_score(classroom_member_id, created_at, test_title, score)
    + delete(classroom_id, user_id)
    + get_user(classroom_member)
    + get_classroom(classroom_member)
}

hide ViewStudentForm circle
hide IStudentForm <<interface>> circle
hide StudentController circle
hide IClassroomMemberDB <<interface>> circle
hide ClassroomMember circle


IStudentForm .down.> ViewStudentForm
IClassroomMemberDB .down.> ClassroomMember
IStudentForm "1"-left-"1" StudentController
StudentController "1"-left-"1" IClassroomMemberDB


@enduml
