@startuml createResource

actor ": Teacher"
boundary ": AddResourceForm"
control ": StudentController"
entity ": ResourceEntity"
entity ": ClassroomMember"

activate ": Teacher"

": Teacher" -> ": AddResourceForm": 1 // request create resource
activate ": AddResourceForm"
": AddResourceForm" -> ": StudentController": 2 // request create resource
activate ": StudentController"
": StudentController" -> ": ClassroomMember": 3 // checking permission to create resource
activate ": ClassroomMember"
alt resource is accessible
    ": ClassroomMember" -->> ": StudentController": 4 // can create resource
    ": StudentController" ->> ": ResourceEntity": 5 // request create resource
    activate ": ResourceEntity"
    ": StudentController" -->> ": AddResourceForm": 7 // create resource successfully
    deactivate ": ResourceEntity"
    ": AddResourceForm" -->> ": Teacher": 8 // create resource successfully
else resource is not accessible
    ": ClassroomMember" -->> ": StudentController": 4.1 // can not create resource
    deactivate ": ClassroomMember"
    ": StudentController" -->> ": AddResourceForm": 4.2 // create resource failed
    deactivate ": StudentController"
    ": AddResourceForm" -->> ": Teacher": 4.3 // create resource failed
end

deactivate ": Teacher"
deactivate ": AddResourceForm"


@enduml