@startuml createClass

actor Teacher
boundary createClassroomForm
control ClassroomController
entity classroomEntity

Teacher -> createClassroomForm: 1 // fill & request create classroom
createClassroomForm -> ClassroomController: 2 // request create classroom
ClassroomController -> classroomEntity: 3 // request checking classroom valid
classroomEntity -> classroomEntity: 4// checking classroom is valid and unique
alt classroom is valid
    classroomEntity -> ClassroomController: 5 // classroom is valid
    ClassroomController ->> classroomEntity: 6 // create classroom
    classroomEntity -> classroomEntity: 7 // create classroom
    ClassroomController -> createClassroomForm: 8 // create classroom successfully
    createClassroomForm -> Teacher: 9 // Classroom created
else classroom is not valid
    classroomEntity -> ClassroomController: 5.1 // classroom is not valid
    ClassroomController -> createClassroomForm: 6.1 // create classroom failed
    createClassroomForm -> Teacher: 7.1 // classroom is not created
end

@enduml