@startuml deleteStudent

actor ":Teacher"
boundary ":AddStudentForm"
control ":StudentController"
entity ":ClassroomEntity"
entity ":ClassroomMember"

activate ":Teacher"
":Teacher" -> ":AddStudentForm": 1 // Delete student from classroom
activate ":AddStudentForm"
":AddStudentForm" -> ":StudentController": 2 // Request delete student to classroom
activate ":StudentController"
":StudentController" -> ":ClassroomMember": 3 // Checking student and class information is valid
activate ":ClassroomMember"
":ClassroomMember" -> ":ClassroomMember": 4 // Checking student and class information is valid
alt student is valid for enroll classroom
    ":ClassroomMember" -> ":StudentController": 5 // student and classroom is valid
    ":StudentController" ->> ":ClassroomEntity": 6 // delete student i from classroom j
    activate ":ClassroomEntity" 
    ":ClassroomEntity" -> ":ClassroomEntity": 7 // delete student to classroom
    ":StudentController" -> ":AddStudentForm": 8 // delete student to classroom successfully
    deactivate ":ClassroomEntity"
    ":AddStudentForm" -> ":Teacher": 9 // student is deleted to classroom

else student is not valid for enroll classroom
    ":ClassroomMember" -> ":StudentController": 5.1 // provided student or classroom is not valid
    deactivate ":ClassroomMember"
    ":StudentController" -> ":AddStudentForm": 6.1 // delete student from classroom failed
    deactivate ":StudentController"
    ":AddStudentForm" -> ":Teacher": 7.1 // student is not deleted from classroom
end

deactivate ":AddStudentForm"
deactivate ":Teacher"

@enduml