@startuml updateClass

actor ": Teacher"
boundary ": UpdateClassroomForm"
control ": ClassroomController"
entity ": ClassroomEntity"

activate ": Teacher"
": Teacher" -> ": UpdateClassroomForm": 1 // fill & request update classroom
activate ": UpdateClassroomForm"
": UpdateClassroomForm" -> ": UpdateClassroomForm": 2 // validate
alt all information is valid
    ": UpdateClassroomForm" -> ": ClassroomController": 3 // request update classroom
    activate ": ClassroomController"
    ": ClassroomController" -> ": ClassroomEntity": 4 // request checking \n classroom is exist and classroom information
    activate ": ClassroomEntity"
    alt classroom is valid
        ": ClassroomEntity" -->> ": ClassroomController": 5 // classroom is exist and information is valid
        ": ClassroomController" ->> ": ClassroomEntity": 6 // update classroom
        ": ClassroomController" -->> ": UpdateClassroomForm": 7 // update classroom successfully
        ": UpdateClassroomForm" -->> ": Teacher": 8 // Classroom updated
    else classroom is not valid
        ": ClassroomEntity" -->> ": ClassroomController": 5.1 // classroom is not valid
        deactivate ": ClassroomEntity"
        ": ClassroomController" -->> ": UpdateClassroomForm": 5.2 // update  classroom failed
        deactivate ": ClassroomController"
        ": UpdateClassroomForm" -->> ": Teacher": 5.3 // classroom is not updated
    end
else some information is missing or invalid
    ": UpdateClassroomForm" -->> ": Teacher": 3.1 // check information again
end

deactivate ": UpdateClassroomForm"
deactivate ": Teacher"

@enduml