@startuml createResource

class Resource <<entity>> {
    id: bigint
    classroom_id: bigint
    uploaded_by: bigint
    resource: string
    created_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // Request create resource ()
}

class ClassroomMember <<entity>> {
    id: bigint
    user_id: bigint
    classroom_id: bigint
    created_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // checking permission to create resource()
}

class CreateResourceForm <<boundary>> {
    // request create resource()
}

class ResourceController <<controller>> {
    // request create resource ()
}

hide Resource <<entity>> circle
hide CreateResourceForm <<boundary>> circle
hide ResourceController <<controller>> circle

ResourceController "1" -left- "1" Resource
ResourceController "1" -right- "1" ClassroomMember
ResourceController "1" -down- "1" CreateResourceForm



@enduml
