@startuml viewResource

class Resource <<entity>> {
    id: bigint
    classroom_id: bigint
    uploaded_by: bigint
    resource: string
    created_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // Request view resource ()
}

class ClassroomMember <<entity>> {
    id: bigint
    user_id: bigint
    classroom_id: bigint
    created_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // checking permission to view resource()
}

class ViewResourceForm <<boundary>> {
    // request view  resource()
}

class ResourceController <<controller>> {
    // request view resource ()
}

hide Resource <<entity>> circle
hide ViewResourceForm <<boundary>> circle
hide ResourceController <<controller>> circle

ResourceController "1" -left- "1" Resource
ResourceController "1" -right- "1" ClassroomMember
ResourceController "1" -down- "1" ViewResourceForm



@enduml
