@startuml addStudent

class ViewStudentForm {
    - classroom_member_id: bigint
    - token: string

    + update_roll_call(token, classroom_member_id)
}

class IStudentForm <<interface>> {
    + update_roll_call(token, classroom_member_id)
}

class StudentController {
    + update_roll_call(token, classroom_member_id, created_at, is_presented)
}

class ClassroomMember {
    - id: bigint
    - user_id: bigint
    - classroom_id: bigint
    - created_at: datetime

    + create(classroom_id, user_id): void
    + read(classroom_id)
    + read(user_id)
    + read(classroom_member_id)
    + read(classroom_id, user_id)
    + update_rollcall(classroom_member_id, created_at, is_presented)
    + update_bonus_point(classroom_member_id, created_at, point)
    + update_score(classroom_member_id, created_at, test_title, score)
    + delete(classroom_id, user_id)
    + get_user(classroom_member)
    + get_classroom(classroom_member)
}

class IClassroomMemberDB <<interface>> {
    + read(classroom_id, user_id)
}


class RollCall {
    - id: bigint
    - classroom_member_id: bigint
    - date: date
    - is_presented: bool
    - created_at: datetime
    - updated_at: datetime

    + create(classroom_member_id, date, is_presented)
    + read(classroom_member_id)
    + read(classroom_member_id, rollcall_id)
    + delete(classroom_member_id, rollcall_id)
}

class IRollCallDB <<interface>> {
    + create(classroom_member_id, date, is_presented)
}

hide ViewStudentForm circle
hide IStudentForm <<interface>> circle
hide StudentController circle
hide IClassroomMemberDB <<interface>> circle
hide ClassroomMember circle
hide IRollCallDB <<interface>> circle
hide RollCall circle


IStudentForm .down.> ViewStudentForm
IClassroomMemberDB .down.> ClassroomMember
IRollCallDB .down.> RollCall
IStudentForm "1"-left-"1" StudentController
StudentController "1"-left-"1" IClassroomMemberDB
StudentController "1"-left-"1" IRollCallDB


@enduml
