@startuml deleteTopic

actor ": User"
boundary ": DeleteTopicForm"
control ": TopicController"
entity ": TopicEntity"
entity ": ClassroomMember"

activate ": User"

": User" -> ": DeleteTopicForm": 1 // request delete topic
activate ": DeleteTopicForm"
": DeleteTopicForm" -> ": TopicController": 2 // request delete topic
activate ": TopicController"
": TopicController" -> ": ClassroomMember": 3 // checking permission to delete topic
activate ": ClassroomMember"
alt can delete topic
    ": ClassroomMember" -> ": TopicController": 4 // can delete topic
    ": TopicController" ->> ": TopicEntity": 5 // request delete topic
    activate ": TopicEntity"
    ": TopicController" -> ": DeleteTopicForm": 7 // delete topic successfully
    deactivate ": TopicEntity"
    ": DeleteTopicForm" -> ": User": 8 // delete topic successfully
else can not delete topic
    ": ClassroomMember" -> ": TopicController": 4.1 // can not delete topic
    deactivate ": ClassroomMember"
    ": TopicController" -> ": DeleteTopicForm": 5.1 // delete topic failed
    deactivate ": TopicController"
    ": DeleteTopicForm" -> ": User": 6.1 // delete topic failed
end

deactivate ": User"
deactivate ": DeleteTopicForm"


@enduml