@startuml viewStudent

actor ": User"
boundary ": ViewStudentForm"
control ": UserController"
entity ": ClassroomMember"

activate ": User"
": User" -> ": ViewStudentForm": 1 // request view student information
activate ": ViewStudentForm"
": ViewStudentForm" -> ": UserController": 2// get all student
activate ": UserController"
": UserController" -> ": ClassroomMember": 3 // get all student in classroom
activate ": ClassroomMember"
": ClassroomMember" -> ": UserController": 4 // list student
deactivate ": ClassroomMember"
": UserController" -> ": ViewStudentForm": 5 // get student in classroom profile successfully
deactivate ": UserController"
": ViewStudentForm" -> ": User": 6 // request get all student in classroom oke
deactivate ": User"

@enduml