@startuml updateScore

actor ": Teacher"
boundary ": UpdateScoreForm"
control ": StudentController"
entity ": Score"
entity ": ClassroomMember"

activate ": Teacher"

": Teacher" -> ": UpdateScoreForm": 1 // request update score
activate ": UpdateScoreForm"
": UpdateScoreForm" -> ": StudentController": 2 // request update score
activate ": StudentController"
": StudentController" -> ": ClassroomMember": 3 // checking information is valid
activate ": ClassroomMember"
alt information is valid
    ": ClassroomMember" -->> ": StudentController": 4 // Information is valid
    ": StudentController" ->> ": Score": 5 // Request update score
    activate ": Score"
    ": StudentController" -->> ": UpdateScoreForm": 6 // Update score done
    deactivate ": Score"
    ": UpdateScoreForm" -->> ": Teacher": 7 // Update score done
else information is not valid
    ": ClassroomMember" -->> ": StudentController": 4.1 // Information is not valid
    deactivate ": ClassroomMember"
    ": StudentController" -->> ": UpdateScoreForm": 4.2 // Score update failed
    deactivate ": StudentController"
    ": UpdateScoreForm" -->> ": Teacher": 4.3 // Score update failed,\n check information again
end

deactivate ": Teacher"
deactivate ": UpdateScoreForm"


@enduml