@startuml createComment

class CreateCommentForm {
    - token: string
    - resource: bigint
    - posted_by: bigint
    - content: string
    - topic_id: bigint

    + create_comment(token, topic_id, posted_by, content, resource)
    + validate(token, topic_id, posted_by, content, resource)
}

class ICommentForm <<interface>> {
    + create_comment(token, topic_id, posted_by, content, resource)
    + validate(token, topic_id, posted_by, content, resource)
}

class CommentController {
    + create_comment(token, topic_id, posted_by, content, resource)
}

class ClassroomMember {
    - id: bigint
    - user_id: bigint
    - classroom_id: bigint
    - created_at: datetime

    + create(classroom_id, user_id): void
    + read(classroom_id)
    + read(user_id)
    + read(classroom_member_id)
    + read(classroom_id, user_id)
    + update_rollcall(classroom_member_id, created_at, is_presented)
    + update_bonus_point(classroom_member_id, created_at, point)
    + update_score(classroom_member_id, created_at, test_title, score)
    + delete(classroom_id, user_id)
    + get_user(classroom_member)
    + get_classroom(classroom_member)
}

class IClassroomMemberDB <<interface>> {
    + read(classroom_id, user_id)
}


class Topic {
    - id: bigint
    - classroom_id: bigint
    - posted_by: bigint
    - title: string
    - content: text
    - has_resource: bool
    - resource_id: bigint
    - created_at: datetime
    - updated_at: datetime

    + create(classroom_id, posted_by, title, content, resource)
    + read(classroom_id)
    + read(posted_by)
    + read(topic_id)
    + delete(topic_id)
}

class ITopicDB <<interface>> {
    + read(topic_id)
}


class Comment {
    - id: bigint
    - topic_id: bigint
    - posted_by: bigint
    - comment: string
    - has_resource: bool
    - resource_id: bigint
    - created_at: datetime
    - updated_at: datetime

    + create(topic_id, posted_by, content, resource)
    + read(topic_id)
    + read(posted_by)
    + read(comment_id)
    + delete(comment_id)
}

class ICommentDB <<interface>> {
    + create(topic_id, posted_by, content, resource)
}

hide CreateCommentForm circle
hide ICommentForm <<interface>> circle
hide CommentController circle
hide IClassroomMemberDB <<interface>> circle
hide ClassroomMember circle
hide ITopicDB <<interface>> circle
hide Topic circle 
hide ICommentDB <<interface>> circle
hide Comment circle 


ICommentForm .down.> CreateCommentForm
IClassroomMemberDB .down.> ClassroomMember
ITopicDB .down.> Topic
ICommentDB .down.> Comment
ICommentForm "1"-left-"1" CommentController
CommentController "1"-left-"1" IClassroomMemberDB
CommentController "1"-left-"1" ITopicDB
CommentController "1"-right-"1" ICommentDB


@enduml
