@startuml
actor ":User"
boundary ":ForgotPasswordForm"
boundary ":ConfirmPasswordForm"
control ":AuthenticationController"
entity ":UserEntity"

activate ":User"
":User" -> ":ForgotPasswordForm" : 1.1 // enter email
activate ":ForgotPasswordForm"
":ForgotPasswordForm" -> ":ForgotPasswordForm" : 1.2 // validate email form

alt email in correct form

":ForgotPasswordForm" -> ":AuthenticationController" : 1.3 // mail form accept
activate ":AuthenticationController"
":AuthenticationController" -> ":UserEntity" : 1.4 // validate email in DB
activate ":UserEntity"

alt email exist
":UserEntity" --> ":AuthenticationController" : 1.5 // email exist msg
":AuthenticationController" --> ":User" : 1.6 // send forgot password email
else email not exist

":UserEntity" --> ":AuthenticationController" : 1.5.1 // email not exist msg
deactivate ":UserEntity"
":AuthenticationController" --> ":ForgotPasswordForm" : 1.6.1 // email not exist msg
deactivate ":AuthenticationController"
":ForgotPasswordForm" --> ":User" : 1.7.1 // email not exist msg
end

else email in wrong form
":ForgotPasswordForm" --> ":User" : 1.3.1 // email in wrong form msg

end
deactivate ":ForgotPasswordForm"
":User" -> ":ConfirmPasswordForm" : 2.1 // send mail
activate ":ConfirmPasswordForm"
":ConfirmPasswordForm" -> ":ConfirmPasswordForm" : 2.2 // validate email form

alt email in correct form

":ConfirmPasswordForm" -> ":AuthenticationController" : 2.3 // mail form accept
activate ":AuthenticationController"
":AuthenticationController" -> ":AuthenticationController" : 2.4 // validate email info

alt all info is provided
":AuthenticationController" -> ":UserEntity" : 2.5 // confirm password
activate ":UserEntity"
deactivate ":UserEntity"
else missing info
":AuthenticationController" --> ":ConfirmPasswordForm" : 2.6.1 // missing inf msg
deactivate ":AuthenticationController"
":ConfirmPasswordForm" --> ":User" : 2.7.1 // missing inf msg
end
else email in wrong form
":ConfirmPasswordForm" --> ":User" : 2.5.1 // email in wrong form msg
deactivate ":ConfirmPasswordForm"
end
deactivate ":User"
@enduml