@startuml
actor ": User"
boundary ": RegisterForm"
boundary ": ConfirmRegisterForm"
control ": AuthenticationController"
entity ": UserEntity"

activate ": User"
": User" -> ": RegisterForm" : 1.1 // enter information
activate ": RegisterForm"
": RegisterForm" -> ": RegisterForm" : 1.2 // validate

alt all info is provided

": RegisterForm" -> ": AuthenticationController" : 1.3 // register
activate ": AuthenticationController"
": AuthenticationController" -> ": UserEntity" : 1.4 // validate register
activate ": UserEntity"

alt id is unique

": UserEntity" --> ": AuthenticationController" : 1.5 // User does not exsit
": AuthenticationController" -> ": UserEntity" : 1.6 // register
": UserEntity" -> ": UserEntity" : 1.7 // create
": UserEntity" --> ": AuthenticationController" : 1.8 // register mail
": AuthenticationController" --> ": User" : 1.9 // register email
else id exits

": UserEntity" --> ": AuthenticationController" : 1.5.1 // User exist msg
deactivate ": UserEntity"
": AuthenticationController" --> ": RegisterForm" : 1.6.1 // User exist msg
deactivate ": AuthenticationController"
": RegisterForm" --> ": User" : 1.7.1 // User exist msg

end

else missing info

": RegisterForm" --> ": User" : 1.3.1 // missing inf msg

end
deactivate ": RegisterForm"
": User" -> ": ConfirmRegisterForm" : 2.1 // open register mail get token
activate ": ConfirmRegisterForm"
": ConfirmRegisterForm" -> ": ConfirmRegisterForm" : 2.2 // validate

alt all info is provided

": ConfirmRegisterForm" -> ": AuthenticationController" : 2.3 // confirm register
activate ": AuthenticationController"
": AuthenticationController" -> ": AuthenticationController" : 2.4 // validate confirmRegister
": AuthenticationController" --> ": User" : 2.5 // send registerEmail


alt all info is provided

": AuthenticationController" -> ": UserEntity" : 2.6 // confirm register
activate ": UserEntity"
deactivate ": UserEntity"
else missing info

": AuthenticationController" --> ": ConfirmRegisterForm" : 2.6.1 // missing inf msg
": ConfirmRegisterForm" --> ": User" : 2.7.1 // missing inf msg

end
deactivate ": ConfirmRegisterForm"

else missing info

": AuthenticationController" --> ": User" : 2.5.1 // missing info msg
deactivate ": AuthenticationController"
end
deactivate ": User"
@enduml