@startuml updateRollCall

class RollCall <<entity>> {
    id: bigint
    classroom_member_id: bigint
    date: date
    is_presented: bool
    created_at: datetime
    updated_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // request make roll call ()
}

class ClassroomMember <<entity>> {
    id: bigint
    user_id: bigint
    classroom_id: bigint
    created_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // checking information is valid ()
}

class UpdateRollCallForm <<boundary>> {
    // request update roll call ()
}

class StudentController <<controller>> {
    // request update roll call ()
}

hide RollCall <<entity>> circle
hide UpdateRollCallForm <<boundary>> circle
hide StudentController <<controller>> circle

StudentController "1" -left- "1" RollCall
StudentController "1" -right- "1" ClassroomMember
StudentController "1" -down- "1" UpdateRollCallForm



@enduml
