@startuml
actor ":User"

activate ":User"
":User" -> ":IAuthenticationForm" : 1.1 // enter email
activate ":IAuthenticationForm"
":IAuthenticationForm" -> ":IAuthenticationForm" : validate(email)

alt email in correct form

":IAuthenticationForm" -> ":AuthenticationController" : forgot_password(email)

activate ":AuthenticationController"
":AuthenticationController" -> ":IUserDB" : validate_forgot_password(email)
activate ":IUserDB"

alt email exist
":IUserDB" --> ":AuthenticationController" : // email exist msg
":AuthenticationController" --> ":User" : send_forgot_password_email(email, forgot_password_token)
else email not exist

":IUserDB" --> ":AuthenticationController" : // email not exist msg
deactivate ":IUserDB"
":AuthenticationController" --> ":IAuthenticationForm" : // email not exist msg
deactivate ":AuthenticationController"
":IAuthenticationForm" --> ":User" : // email not exist msg
end

else email in wrong form
":IAuthenticationForm" --> ":User" : // email in wrong form msg

end
deactivate ":IAuthenticationForm"
":User" -> ":ConfirmPasswordForm" : 2.1 // send mail
activate ":ConfirmPasswordForm"
":ConfirmPasswordForm" -> ":ConfirmPasswordForm" : validate(forgot_password_token, new_password1, new_password2)
alt email in correct form

":ConfirmPasswordForm" -> ":AuthenticationController" : confirm_forgot_password(forgot_password_token, new_password1)
activate ":AuthenticationController"
":AuthenticationController" -> ":AuthenticationController" : validate_confirm_password(forgot_password_token, new_password1, new_password2)


alt all info is provided
":AuthenticationController" -> ":IUserDB" : confirm_password(forgot_password, new_password1)

activate ":IUserDB"
deactivate ":IUserDB"
else missing info
":AuthenticationController" --> ":ConfirmPasswordForm" : // missing inf msg
deactivate ":AuthenticationController"
":ConfirmPasswordForm" --> ":User" : // missing inf msg
end
else email in wrong form
":ConfirmPasswordForm" --> ":User" : // email in wrong form msg
deactivate ":ConfirmPasswordForm"
end
deactivate ":User"
@enduml