@startuml
actor ":User"

activate ":User"
":User" -> ":LogoutForm" : 1 // enter information
activate ":LogoutForm"
":LogoutForm" -> ":LogoutForm" : validate(token)
alt all info is provided

":LogoutForm" -> ":AuthenticationController" : logout(token)
activate ":AuthenticationController"
":AuthenticationController" -> ":AuthenticationController" : validate_logout(token)

alt correct info

":AuthenticationController" -> ":IUserDB" : logout(token)
activate ":IUserDB"
":IUserDB" -> ":IUserDB" : delete_token(token)
":IUserDB" -> ":AuthenticationController" :  // logout accept msg
deactivate ":IUserDB"
":AuthenticationController" -> ":User" :  // logout accept msg

else invalid info

":AuthenticationController" -> ":LogoutForm" : // invalid inf msg
deactivate ":AuthenticationController"
":LogoutForm" -> ":User" : // invalid inf msg

end

else missing info

":LogoutForm" -> ":User" : // missing inf msg
deactivate ":LogoutForm"
deactivate ":User"
end
@enduml