@startuml
actor ": User"

activate ": User"
": User" -> ": IAuthenticationForm" : 1 // enter information
activate ": IAuthenticationForm"
": IAuthenticationForm" -> ": IAuthenticationForm" : validate(token, old_password, new_password1, new_password2)

alt all info is provided

": IAuthenticationForm" -> ": AuthenticationController" : reset_password(token, old_password, new_password1)
activate ": AuthenticationController"
": AuthenticationController" -> ": UserEntity" : validate_reset_password(token, old_password, new_password1, new_password2)

alt correct info
activate ": UserEntity"
": UserEntity" --> ": AuthenticationController" : // correct password msg
": AuthenticationController" -> ": UserEntity" : reset_password(token, old_password, new_password1)


": UserEntity" -> ": UserEntity" : reset_password(token, old_password, new_password1)
": UserEntity" --> ": AuthenticationController" : // new password accept msg
deactivate ": UserEntity"
": AuthenticationController" --> ": User" : // new password accept msg

else invalid info

": AuthenticationController" --> ": IAuthenticationForm" : // invalid inf msg
deactivate ": AuthenticationController"
": IAuthenticationForm" --> ": User" : // invalid inf msg

end

else missing info

": IAuthenticationForm" --> ": User" : // missing inf msg
deactivate ": IAuthenticationForm"
deactivate ": User"
end
@enduml