@startuml
actor ":User"

activate ":User"
":User" -> ":ResetPasswordForm" : 1 // enter information
activate ":ResetPasswordForm"
":ResetPasswordForm" -> ":ResetPasswordForm" : validate(token, old_password, new_password1, new_password2)

alt all info is provided

":ResetPasswordForm" -> ":AuthenticationController" : reset_password(token, old_password, new_password1)
activate ":AuthenticationController"
":AuthenticationController" -> ":UserEntity" : validate_reset_password(token, old_password, new_password1, new_password2)

alt correct info
activate ":UserEntity"
":UserEntity" -> ":AuthenticationController" : // correct password msg
":AuthenticationController" -> ":UserEntity" : reset_password(token, old_password, new_password1)


":UserEntity" -> ":UserEntity" : reset_password(token, old_password, new_password1)
":UserEntity" -> ":AuthenticationController" : // new password accept msg
deactivate ":UserEntity"
":AuthenticationController" -> ":User" : // new password accept msg

else invalid info

":AuthenticationController" -> ":ResetPasswordForm" : // invalid inf msg
deactivate ":AuthenticationController"
":ResetPasswordForm" -> ":User" : // invalid inf msg

end

else missing info

":ResetPasswordForm" -> ":User" : // missing inf msg
deactivate ":ResetPasswordForm"
deactivate ":User"
end
@enduml