@startuml
actor ": User"

activate ": User"
": User" -> ": IAuthenticationForm" :  // enter information
activate ": IAuthenticationForm"
": IAuthenticationForm" -> ": IAuthenticationForm" : validate(token,\n first_name, \nlast_name, \ndob, school_id, \nphone_number, avatar)

alt all info is provided

": IAuthenticationForm" -> ": AuthenticationController" : update_profile(token, \nfirst_name, \nlast_name, dob, school_id, \nphone_number, avatar)
activate ": AuthenticationController"
": AuthenticationController" -> ": IUserDB" : view_profile(token)
": IUserDB" -> ": IUserDB" : update_profile(token,\n first_name, \nlast_name,\n dob, school_id, \nphone_number, avatar)


": IUserDB" --> ": AuthenticationController" : // info view msg
": AuthenticationController" --> ": IAuthenticationForm" : // info view msg
": IAuthenticationForm"  --> ": User" : // info view msg
else missing info

": IAuthenticationForm" --> ": User" : // missing inf msg
deactivate ": IAuthenticationForm"
deactivate ": User"
end
@enduml