@startuml
actor ":User"

activate ":User"
":User" -> ":IAuthenticationForm" : 1 // enter information
activate ":IAuthenticationForm"
":IAuthenticationForm" -> ":IAuthenticationForm" : validate(token)

alt all info is provided

":IAuthenticationForm" -> ":AuthenticationController" : view_profile(token)
activate ":AuthenticationController"
":AuthenticationController" -> ":IUserDB" : view_profile(token)
":IUserDB" -> ":IUserDB" : get_user(token)

":IUserDB" --> ":AuthenticationController" : // info view msg
":AuthenticationController"  --> ":IAuthenticationForm" : // info view msg
":IAuthenticationForm" --> ":User" : // info view msg
else missing info

":IAuthenticationForm" --> ":User" : // missing inf msg
deactivate ":IAuthenticationForm"
deactivate ":User"
end
@enduml