@startuml updateClass

class Classroom <<entity>> {
    id: bigint
    classroom_name: string
    description: string
    teacher_id: bigint
    created_at: datetime
    updated_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // delete student from classroom()
}

class ClassroomMember <<entity>> {
    id: bigint
    user_id: bigint
    classroom_id: bigint
    created_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // checking student and class information is valid()
}

class ViewClassroomForm <<boundary>> {
    // delete student from class ()
}

class StudentController <<controller>> {
    // request add student to classroom ()
}

hide Classroom <<entity>> circle
hide ViewClassroomForm <<boundary>> circle
hide StudentController <<controller>> circle

StudentController "1" -left- "1" Classroom
StudentController "1" -right- "1" ClassroomMember
StudentController "1" -down- "1" ViewClassroomForm



@enduml
