@startuml updateClass

class ClassroomMember <<entity>> {
    id: bigint
    user_id: bigint
    classroom_id: bigint
    created_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // get all student in classroom ()
}

class ViewStudentForm <<boundary>> {
    // request get all student in classroom oke ()
}

class StudentController <<controller>> {
    // get all student ()
}

hide ViewStudentForm <<boundary>> circle
hide StudentController <<controller>> circle
hide ClassroomMember <<entity>> circle

StudentController "1" -right- "1" ClassroomMember
StudentController "1" -down- "1" ViewStudentForm



@enduml
