@startuml deleteTopic
activate ": User"

": User" -->> ": ITopicForm": 1 // request delete topic
activate ": ITopicForm"
": ITopicForm" -> ": TopicController": delete_topic(token, topic_id)
activate ": TopicController"
": TopicController" -> ": IClassroomMemberDB": read(classroom_id, user_id)
activate ": IClassroomMemberDB"
deactivate ": IClassroomMemberDB"
alt can delete topic (is teacher of that class or user who create topic)
    ": TopicController" -> ": ITopicDB": read(topic_id)
    activate ": ITopicDB"
    alt topic is exist
        ": TopicController" ->> ": ITopicDB": delete(topic_id)
        deactivate ": ITopicDB"
        ": ITopicForm" -->> ": User": 8 // delete topic successfully
    else topic is not exist
        ": ITopicForm" -->> ": User": // topic is not exist
    end
    
else can not delete topic
    ": TopicController" -> ": ITopicForm": 5.1 // delete topic failed
    deactivate ": TopicController"
    ": ITopicForm" -->> ": User": // not have permission for delete topic
end

deactivate ": User"
deactivate ": ITopicForm"


@enduml