@startuml deleteClass

actor ": Teacher"
boundary ": IClassroomForm"
control ": ClassroomController"
entity ": ClassroomEntity"

activate ": Teacher"
": Teacher" -> ": IClassroomForm": 1 // request delete classroom
activate ": IClassroomForm"
": IClassroomForm" -> ": IClassroomForm": 2 // validate
alt all information is filled
    ": IClassroomForm" -> ": ClassroomController": 3 // request delete classroom
    activate ": ClassroomController"
    ": ClassroomController" -> ": ClassroomEntity": 4 // request checking \n classroom is exist
    activate ": ClassroomEntity"
    alt classroom is valid
        ": ClassroomEntity" -> ": ClassroomController": 5 // classroom is exist 
        ": ClassroomController" ->> ": ClassroomEntity": 6 // request delete classroom
        ": ClassroomController" -> ": IClassroomForm": 7 // delete classroom successfully
        ": IClassroomForm" -> ": Teacher": 8 // Classroom deleted
    else classroom is not valid
        ": ClassroomEntity" -> ": ClassroomController": 4.1 // classroom is not exist
        deactivate ": ClassroomEntity"
        ": ClassroomController" -> ": IClassroomForm": 5.1 // delete  classroom failed
        deactivate ": ClassroomController"
        ": IClassroomForm" -> ": Teacher": 6.1 // classroom is not deleted
    end
else some information is missing
    ": IClassroomForm" -> ": Teacher": 3.1 // check information again
end

deactivate ": IClassroomForm"
deactivate ": Teacher"

@enduml