@startuml updateClass

actor ": Teacher"
boundary ": CreateClassroomForm"
control ": ClassroomController"
entity ":ClassroomEntity"

activate ": Teacher"
": Teacher" -> ": CreateClassroomForm": 1 // fill & request update classroom
activate ": CreateClassroomForm"
": CreateClassroomForm" -> ": CreateClassroomForm": 2 // validate
alt all information is valid
    ": CreateClassroomForm" -> ": ClassroomController": 3 // request update classroom
    activate ": ClassroomController"
    ": ClassroomController" -> ":ClassroomEntity": 4 // request checking \n classroom is exist and classroom information
    activate ":ClassroomEntity"
    alt classroom is valid
        ":ClassroomEntity" -> ": ClassroomController": 5 // classroom is exist and information is valid
        ": ClassroomController" ->> ":ClassroomEntity": 6 // update classroom
        ": ClassroomController" -> ": CreateClassroomForm": 7 // update classroom successfully
        ": CreateClassroomForm" -> ": Teacher": 8 // Classroom updated
    else classroom is not valid
        ":ClassroomEntity" -> ": ClassroomController": 5.1 // classroom is not valid
        deactivate ":ClassroomEntity"
        ": ClassroomController" -> ": CreateClassroomForm": 6.1 // update  classroom failed
        deactivate ": ClassroomController"
        ": CreateClassroomForm" -> ": Teacher": 7.1 // classroom is not updated
    end
else some information is missing or invalid
    ": CreateClassroomForm" -> ": Teacher": 3.1 // check information again
end

deactivate ": CreateClassroomForm"
deactivate ": Teacher"

@enduml