@startuml viewClass

actor ":User"
boundary ": IClassroomForm"
control ": ClassroomController"
entity ": ClassroomMember"

activate ":User"
":User" -> ": IClassroomForm": 1 // request get class info
activate ": IClassroomForm"
": IClassroomForm" -> ": ClassroomController": 2 // request get classroom information
activate ": ClassroomController"
": ClassroomController" -> ": ClassroomMember": 3 // request checking \n classroom is exist
activate ": ClassroomMember"
alt classroom is valid
    ": ClassroomMember" -> ": ClassroomController": 4 // classroom is exist
    ": ClassroomController" -> ": ClassroomMember": 5 // get classroom information
    ": ClassroomMember" -> ": ClassroomController": 6 // classroom information
    ": ClassroomController" -> ": IClassroomForm": 7 // get classroom info successfully
    ": IClassroomForm" -> ":User": 8 // Classroom information
else classroom is not valid
    ": ClassroomMember" -> ": ClassroomController": 4.1 // classroom is not exist
    deactivate ": ClassroomMember"
    ": ClassroomController" -> ": IClassroomForm": 5.1 // cannot get classroom information
    deactivate ": ClassroomController"
    ": IClassroomForm" -> ":User": 6.1 // classroom invalid
end

deactivate ": IClassroomForm"
deactivate ":User"

@enduml