@startuml
actor ":User"
boundary ":LogoutForm"
control ":AuthenticationController"
entity ":UserEntity"
activate ":User"
":User" -> ":LogoutForm" : 1 // enter information
activate ":LogoutForm"
":LogoutForm" -> ":LogoutForm" : 2 // validate
alt all info is provided

":LogoutForm" -> ":AuthenticationController" : 3 // logout
activate ":AuthenticationController"
":AuthenticationController" -> ":AuthenticationController" : 4 // validate

alt correct info

":AuthenticationController" -> ":UserEntity" : 5 // logout
activate ":UserEntity"
":UserEntity" -> ":UserEntity" : 6 // delete token
":UserEntity" --> ":AuthenticationController" : 7 // logout accept msg
deactivate ":UserEntity"
":AuthenticationController" --> ":User" : 8 // logout accept msg

else invalid info

":AuthenticationController" --> ":LogoutForm" : 5.1 // invalid inf msg
deactivate ":AuthenticationController"
":LogoutForm" --> ":User" : 5.2 // invalid inf msg

end

else missing info

":LogoutForm" --> ":User" : 4.1 // missing inf msg
deactivate ":LogoutForm"
deactivate ":User"
end
@enduml