@startuml
actor ":User"
boundary ":ResetPasswordForm"
control ":AuthenticationController"
entity ":UserEntity"
activate ":User"
":User" -> ":ResetPasswordForm" : 1 // enter information
activate ":ResetPasswordForm"
":ResetPasswordForm" -> ":ResetPasswordForm" : 2 // validate
alt all info is provided

":ResetPasswordForm" -> ":AuthenticationController" : 3 // reset password
activate ":AuthenticationController"
":AuthenticationController" -> ":UserEntity" : 4 // validate

alt correct info
activate ":UserEntity"
":UserEntity" -> ":AuthenticationController" : 5 // correct password msg
":AuthenticationController" -> ":UserEntity" : 6 // reset password

":UserEntity" -> ":UserEntity" : 7 // reset password
":UserEntity" -> ":AuthenticationController" : 8 // new password accept msg
deactivate ":UserEntity"
":AuthenticationController" -> ":User" : 9 // new password accept msg

else invalid info

":AuthenticationController" -> ":ResetPasswordForm" : 5.1 // invalid inf msg
deactivate ":AuthenticationController"
":ResetPasswordForm" -> ":User" : 5.2 // invalid inf msg

end

else missing info

":ResetPasswordForm" -> ":User" : 4.1 // missing inf msg
deactivate ":ResetPasswordForm"
deactivate ":User"
end
@enduml