@startuml addStudent

activate ": Teacher"
": Teacher" -->> ": IStudentForm": // Add student to classroom
activate ": IStudentForm"
": IStudentForm" -> ": IStudentForm": validate(token, classroom_id, user_id)
alt all information is filled and valid
    ": IStudentForm" -> ": StudentController": add_student(token, classroom_id, user_id)
    activate ": StudentController"
    ": StudentController" -> ": StudentController": validate_add_student(token, classroom_id, user_id)
    alt student is valid for enroll classroom
        ": StudentController" -> ": IClassroomMemberDB": read(classroom_id, user_id)
        activate ": IClassroomMemberDB"
        alt student is not exist in classroom
            ": StudentController" ->> ": IClassroomDB": create(classroom_id, user_id)
            deactivate ": StudentController"
            deactivate ": IClassroomMemberDB"
            activate ": IClassroomDB"
            ": IStudentForm" -->> ": Teacher": // student is added to classroom
            deactivate ": IClassroomDB"
        else student is exist in classroom
            ": IStudentForm" -->> ": Teacher": // student is exist in classroom
        end

    else student is not valid for enroll classroom
        ": IStudentForm" -->> ": Teacher": // student is not valid to  added to classroom
    end
else some information is missing or invalid
   ": IStudentForm" -->> ": Teacher": // Check information again
end

deactivate ": IStudentForm"
deactivate ": Teacher"

@enduml