@startuml viewStudent
activate ": User"
": User" -->> ": IStudentForm": // request view student information
activate ": IStudentForm"
": IStudentForm" -> ": StudentController": view_profile(token, classroom_id)
activate ": StudentController"
": StudentController" -> ": IClassroomMemberDB": get_user(classroom_id)
activate ": IClassroomMemberDB"
deactivate ": IClassroomMemberDB"
deactivate ": StudentController"
": IStudentForm" -->> ": User": // list all classroom
deactivate ": User"

@enduml