@startuml viewComment

actor ": User"
boundary ": ViewCommentForm"
control ": CommentController"
entity ": Comment"
entity ": ClassroomMember"

activate ": User"

": User" -> ": ViewCommentForm": 1 // request view comment 
activate ": ViewCommentForm"
": ViewCommentForm" -> ": CommentController": 2 // request view comment
activate ": CommentController"
": CommentController" -> ": ClassroomMember": 3 // checking permission to view comment
activate ": ClassroomMember"
alt can delete topic
    ": ClassroomMember" -->> ": CommentController": 4 // can view comment
    ": CommentController" ->> ": Comment": 5 // request view comment
    activate ": Comment"
    ": CommentController" --> ": ViewCommentForm": 7 // return comments
    deactivate ": Comment"
    ": ViewCommentForm" -->> ": User": 8 // return comments
else can not delete topic
    ": ClassroomMember" -->> ": CommentController": 4.1 // not have permission to view comment
    deactivate ": ClassroomMember"
    ": CommentController" -->> ": ViewCommentForm": 4.2 // can not view comment
    deactivate ": CommentController"
    ": ViewCommentForm" -->> ": User": 4.3 // can not view comment
end

deactivate ": User"
deactivate ": ViewCommentForm"


@enduml