@startuml viewResource

class ViewResourceForm {
    - token: string
    - resource_id: bigint

    + view_resource(token, resource_id)
}

class IResourceForm <<interface>> {
    + view_resource(token, resource_id)
}

class ResourceController {
    + view_resource(token, resource_id)
}

class ClassroomMember {
    - id: bigint
    - user_id: bigint
    - classroom_id: bigint
    - created_at: datetime

    + create(classroom_id, user_id): void
    + read(classroom_id)
    + read(user_id)
    + read(classroom_member_id)
    + read(classroom_id, user_id)
    + update_rollcall(classroom_member_id, created_at, is_presented)
    + update_bonus_point(classroom_member_id, created_at, point)
    + update_score(classroom_member_id, created_at, test_title, score)
    + delete(classroom_id, user_id)
    + get_user(classroom_member)
    + get_classroom(classroom_member)
}

class IClassroomMemberDB <<interface>> {
    + read(classroom_id, user_id)
}


class Resource {
    -id: bigint
    -classroom_id: bigint
    -uploaded_by: bigint
    -resource: string
    -created_at: datetime

    + save_resource()
    + get_resource_url()
    + create(classroom_id, uploaded_by, resource_url)
    + read(classroom_id)
    + read(uploaded_by)
    + read(resource_id)
    + delete(resource_id)
}

class IResourceDB <<interface>> {
    + read(resource_id)
}

hide ViewResourceForm circle
hide IResourceForm <<interface>> circle
hide ResourceController circle
hide IClassroomMemberDB <<interface>> circle
hide ClassroomMember circle
hide IResourceDB <<interface>> circle
hide Resource circle 


IResourceForm .down.> ViewResourceForm
IClassroomMemberDB .down.> ClassroomMember
IResourceDB .down.> Resource
IResourceForm "1"-left-"1" ResourceController
ResourceController "1"-left-"1" IClassroomMemberDB
ResourceController "1"-left-"1" IResourceDB


@enduml
