@startuml login

class User <<entity>> {
    id: bigint
    email: string
    password: string
    first_name: string
    last_name: string
    dob: date
    school_id: string
    phone_number: string
    avatar_url: string
    token: string
    last_logged_in: datetime
    is_banned: bool
    is_admin: bool
    is_verify: bool
    created_at: datetime
    updated_at: datetime

    // create ()
    // read ()
    // update ()
    // delete ()
    // get user ()
    // get classrooms ()
    // get token ()
    // delete token ()
}

class LogoutForm <<boundary>> {
    // validate ()
    // logout ()
}

class AuthenticationController <<controller>> {
    // validate logout ()
    // logout ()
}

hide User <<entity>> circle
hide LogoutForm <<boundary>> circle
hide AuthenticationController <<controller>> circle

AuthenticationController "1" -left- "1" User
AuthenticationController "1" -down- "1" LogoutForm



@enduml
