@startuml createClass

class Classroom <<entity>> {
    id: bigint
    classroom_name: string
    description: string
    teacher_id: bigint
    created_at: datetime
    updated_at: datetime

    // create ( )
    // read ( )
    // delete ( )
    // update ( )
    // request checking classroom valid 
}

class CreateClassroomForm <<boundary>> {
    // validate ( )
    // create class room ( )
}

class ClassroomController <<controller>> {
    // validate create classroom ( )
    // create class room ( )
    // request create classroom( )
}

hide Classroom <<entity>> circle
hide CreateClassroomForm <<boundary>> circle
hide ClassroomController <<controller>> circle

ClassroomController "1" -left- "1" Classroom
ClassroomController "1" -down- "1" CreateClassroomForm



@enduml
