@startuml updateClass

class Classroom <<entity>> {
    id: bigint
    classroom_name: string
    description: string
    teacher_id: bigint
    created_at: datetime
    updated_at: datetime

    // create ( )
    // read ( )
    // delete ( )
    // update ( )
    // request checking classroom is exist( )
}

class ViewClassroomForm <<boundary>> {
    // validate ( )
    // view class room ( )
}

class ClassroomController <<controller>> {
    // request get classroom information( )
}

hide Classroom <<entity>> circle
hide ViewClassroomForm <<boundary>> circle
hide ClassroomController <<controller>> circle

ClassroomController "1" -left- "1" Classroom
ClassroomController "1" -down- "1" ViewClassroomForm



@enduml
