@startuml bonusPoint
class BonusPoint {
    - id: bigint
    - classroom_member_id: bigint
    - date: date
    - point: int
    - created_at: datetime
    - updated_at: datetime

    + get_id(): bigint
    + get_classroom_member_id(): bigint
    + set_classroom_member_id(bigint)
    + get_date(): date
    + set_date(date)
    + get_point(): int
    + set_point(int)
    + get_created_at(): datetime
    + get_updated_at(): datetime
}
@enduml