@startuml classroomMember
class ClassroomMember {
    - id: bigint
    - user_id: bigint
    - classroom_id: bigint
    - created_at: datetime

    + get_id(): bigint
    + get_user_id(): bigint
    + set_user_id(bigint)
    + get_classroom_id(): bigint
    + set_classroom_id(bigint)
    + get_created_at(): datetime
    + get_updated_at(): datetime
}
@enduml