@startuml classroom
class Classroom {
    - id: bigint
    - classroom_name: string
    - description: string
    - teacher_id: bigint
    - created_at: datetime
    - updated_at: datetime

    + get_id(): bigint
    + get_classroom_name(): string
    + set_classroom_name(string)
    + get_description(): string
    + set_description(string)
    + get_teacher_id(): string
    + set_teacher_id(string)
    + get_created_at(): datetime
    + get_updated_at(): datetime
}
@enduml