@startuml resource
class Resource {
    -id: bigint
    -classroom_id: bigint
    -uploaded_by: bigint
    -resource: string
    -created_at: datetime

    + get_id(): bigint
    + get_classroom_id(): bigint
    + set_classroom_id(bigint)
    + get_uploaded_by(): bigint
    + set_uploaded_by(bigint)
    + get_resource(): string
    + set_resource(string)
    + get_created_at(): datetime
    + get_updated_at(): datetime
}

@enduml