@startuml deleteStudent

actor ": Teacher"
boundary ": AddStudentForm"
control ": StudentController"
entity ": ClassroomEntity"
entity ": ClassroomMember"

activate ": Teacher"
": Teacher" -> ": AddStudentForm": 1 // Delete student from classroom
activate ": AddStudentForm"
": AddStudentForm" -> ": StudentController": 2 // Request delete student to classroom
activate ": StudentController"
": StudentController" -> ": ClassroomMember": 3 // Checking student and class information is valid
activate ": ClassroomMember"
alt student is exist in classroom
    ": ClassroomMember" -> ": StudentController": 4 // student and classroom is valid
    ": StudentController" ->> ": ClassroomEntity": 5 // delete student i from classroom j
    activate ": ClassroomEntity" 
    ": StudentController" -> ": AddStudentForm": 6 // delete student to classroom successfully
    deactivate ": ClassroomEntity"
    ": AddStudentForm" -> ": Teacher": 7 // student is deleted to classroom

else student is not exist in classroom
    ": ClassroomMember" -> ": StudentController": 4.1 // provided student or classroom is not valid
    deactivate ": ClassroomMember"
    ": StudentController" -> ": AddStudentForm": 5.1 // delete student from classroom failed
    deactivate ": StudentController"
    ": AddStudentForm" -> ": Teacher": 6.1 // student is not deleted from classroom
end

deactivate ": AddStudentForm"
deactivate ": Teacher"

@enduml