@startuml viewStudent

actor ":Student"
boundary ":ViewStudentForm"
control ": StudentController"
entity ": StudentEntity"

activate ":Student"
":Student" -> ":ViewStudentForm": 1 // request view student information
activate ":ViewStudentForm"
":ViewStudentForm" -> ": StudentController": 2// get student profile
activate ": StudentController"
": StudentController" -> ": StudentEntity": 3 // get student information
activate ": StudentEntity"
": StudentEntity" -> ": StudentController": 4 // student information
deactivate ": StudentEntity"
": StudentController" -> ":ViewStudentForm": 5 // get student profile successfully
deactivate ": StudentController"
":ViewStudentForm" -> ":Student": 6 // request get student oke
deactivate "Student"

@enduml