@startuml viewStudent

actor ": Student"
boundary ": ViewStudentForm"
control ": StudentController"
entity ": ClassroomMember"

activate ": Student"
": Student" -> ": ViewStudentForm": 1 // request view student information
activate ": ViewStudentForm"
": ViewStudentForm" -> ": StudentController": 2// get all student
activate ": StudentController"
": StudentController" -> ": ClassroomMember": 3 // get all student in classroom
activate ": ClassroomMember"
": ClassroomMember" -> ": StudentController": 4 // list student
deactivate ": ClassroomMember"
": StudentController" -> ": ViewStudentForm": 5 // get student in classroom profile successfully
deactivate ": StudentController"
": ViewStudentForm" -> ": Student": 6 // request get all student in classroom oke
deactivate ": Student"

@enduml