@startuml createClass

actor ": Teacher"

activate ": Teacher"
": Teacher" ->> ": IClassroomForm": 1 // fill information
activate ": IClassroomForm"
": IClassroomForm" -> ": IClassroomForm": validate(classroom_name, description)
alt all information is filled
    ": IClassroomForm" -> ": ClassroomController": create_classroom(token, classroom_name, description)
    activate ": ClassroomController"
    ": ClassroomController" -> ": ClassroomController": validate_create_classroom(token, classroom_name, description)
    activate ": IClassroomDB"
    alt classroom is valid 
        ": ClassroomController" ->> ": IClassroomDB": create(classroom_name, description, teacher_id)
        ": IClassroomForm" -->> ": Teacher": // Classroom created
    else classroom is not valid
        deactivate ": IClassroomDB"
        deactivate ": ClassroomController"
        ": IClassroomForm" -->> ": Teacher": // classroom is not created
    end
else some information is missing
    ": IClassroomForm" -->> ": Teacher": // check information again
end

deactivate ": IClassroomForm"
deactivate ": Teacher"

@enduml