@startuml deleteClass

activate ": Teacher"
": Teacher" -->> ": IClassroomForm": // request delete classroom
activate ": IClassroomForm"
": IClassroomForm" -> ": IClassroomForm": validate(token, classroom_id)
alt all information is filled
    ": IClassroomForm" -> ": ClassroomController": delete_classroom(token, classroom_id)
    activate ": ClassroomController"
    ": ClassroomController" -> ": IClassroomDB": get(classroom_id)
    activate ": IClassroomDB"
    alt classroom is exist
        ": ClassroomController" ->> ": IClassroomDB": delete(classroom_id)
        ": IClassroomForm" -->> ": Teacher": Classroom deleted
    else classroom is not exist
        deactivate ": IClassroomDB"
        deactivate ": ClassroomController"
        ": IClassroomForm" -->> ": Teacher": classroom is not deleted
    end
else some information is missing
    ": IClassroomForm" -->> ": Teacher": check information again
end

deactivate ": IClassroomForm"
deactivate ": Teacher"

@enduml