@startuml deleteClass

actor ":Teacher"
boundary ":CreateClassroomForm"
control ":ClassroomController"
entity ":ClassroomEntity"

activate ":Teacher"
":Teacher" -->> ":CreateClassroomForm": // request delete classroom
activate ":CreateClassroomForm"
":CreateClassroomForm" -> ":CreateClassroomForm": validate(token, classroom_id)
alt all information is filled
    ":CreateClassroomForm" -> ":ClassroomController": delete_classroom(token, classroom_id)
    activate ":ClassroomController"
    ":ClassroomController" -> ":ClassroomEntity": get(classroom_id)
    activate ":ClassroomEntity"
    alt classroom is exist
        ":ClassroomController" ->> ":ClassroomEntity": delete(classroom_id)
        ":CreateClassroomForm" -->> ":Teacher": Classroom deleted
    else classroom is not exist
        deactivate ":ClassroomEntity"
        deactivate ":ClassroomController"
        ":CreateClassroomForm" -->> ":Teacher": 6.1 // classroom is not deleted
    end
else some information is missing
    ":CreateClassroomForm" -->> ":Teacher": 3.1 // check information again
end

deactivate ":CreateClassroomForm"
deactivate ":Teacher"

@enduml