@startuml updateClass

class BonusPoint <<entity>> {
    id: bigint
    classroom_member_id: bigint
    date: date
    point: int
    created_at: datetime
    updated_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // Request update bonus point ()
}

class ClassroomMember <<entity>> {
    id: bigint
    user_id: bigint
    classroom_id: bigint
    created_at: datetime

    // create ()
    // read ()
    // delete ()
    // update ()
    // checking information is valid()
}

class ViewClassroomForm <<boundary>> {
    // request update bonus point()
}

class StudentController <<controller>> {
    // request update bonus point ()
}

hide BonusPoint <<entity>> circle
hide ViewClassroomForm <<boundary>> circle
hide StudentController <<controller>> circle

StudentController "1" -left- "1" BonusPoint
StudentController "1" -right- "1" ClassroomMember
StudentController "1" -down- "1" ViewClassroomForm



@enduml
