@startuml updateBonusPoint


activate ": Teacher"

": Teacher" -->> ": IStudentForm": 1 // request update bonus point
activate ": IStudentForm"
": IStudentForm" -> ": StudentController": update_bonus_point(token, classroom_member_id, created_at, bonus_point)
activate ": StudentController"
": StudentController" -> ": IClassroomMemberDB": read(classroom_id, user_id)
activate ": IClassroomMemberDB"
deactivate ": IClassroomMemberDB"
alt student is in classroom
    ": StudentController" ->> ": BonusPointDB": create(classroom_member_id, date, point)
    activate ": BonusPointDB"
    deactivate ": BonusPointDB"
    ": IStudentForm" -->> ": Teacher": // Update bonus point done
else student is not in classroom
    deactivate ": StudentController"
    ": IStudentForm" -->> ": Teacher": 6.1 // Bonus point update failed,\n check information again
end

deactivate ": Teacher"
deactivate ": IStudentForm"


@enduml